ClassBridge/ClassBridge-BE

.github/ISSUE_TEMPLATE/issue--bug.md
.github/ISSUE_TEMPLATE/issue--feature.md

Docs: Update issue templates

---

src/main/java/com/linked/classbridge/dto/ErrorResponse.java
src/main/java/com/linked/classbridge/dto/SuccessResponse.java

- ErrorResponse, SuccessResponse 파일에 @RequiredArgsConstructor 제거 (record 타입)
**AS-IS**
**TO-BE**

fix (ErrorResponse, SuccessResponse) : bug fix

---

build.gradle
src/main/java/com/linked/classbridge/config/JpaAuditingConfiguration.java
src/main/java/com/linked/classbridge/config/SwaggerConfig.java
src/main/java/com/linked/classbridge/controller/HelloController.java
src/main/java/com/linked/classbridge/domain/BaseEntity.java
src/main/java/com/linked/classbridge/domain/Hello.java
src/main/java/com/linked/classbridge/dto/HelloDto.java
src/main/java/com/linked/classbridge/dto/SuccessResponse.java
src/main/java/com/linked/classbridge/exception/GlobalExceptionHandler.java
src/main/java/com/linked/classbridge/exception/RestApiException.java
src/main/java/com/linked/classbridge/repository/HelloRepository.java
src/main/java/com/linked/classbridge/service/HelloService.java
src/main/java/com/linked/classbridge/type/ErrorCode.java
src/main/java/com/linked/classbridge/type/ResponseMessage.java
src/main/resources/application-local.yml
src/main/resources/logback-spring.xml

**TO-BE**
- GlobalExceptionHandler 추가
- 커스텀 excpetion 추가
- Swagger 설정 추가
- 공통 response message 를 추가하고 SuccessResponse에서 사용하도록 수정
- 로거(logback) 추가
- 테스트용 hello api 추가
closes #20

feat(common methods): add common methods like global exception and hello api

---

src/main/java/com/linked/classbridge/config/SecurityConfig.java
src/main/java/com/linked/classbridge/controller/UserController.java
src/test/java/com/linked/classbridge/controller/OneDayClassControllerTest.java
src/test/java/com/linked/classbridge/controller/ReviewControllerTest.java
src/test/java/com/linked/classbridge/controller/UserControllerTest.java

유저 정보를 토큰에서 가져오는 방식으로 변경하면서 테스트 코드를 일부 수정했습니다.

test(review) : fix review test code 

---

src/test/java/com/linked/classbridge/controller/OneDayClassControllerTest.java
src/test/java/com/linked/classbridge/controller/TutorControllerTest.java
src/test/java/com/linked/classbridge/service/ReviewServiceTest.java

fix: 리뷰 테스트 코드 수정

---

src/main/resources/application-local.yml
src/test/http/reservation.http
src/test/java/com/linked/classbridge/service/KakaoPaymentServiceTest.java
src/test/java/com/linked/classbridge/service/ReservationServiceTest.java

테스트 코드 오류 수정하였습니다.
- 결제 환불 URL을 수정하기 위해 application-local.yml을 업데이트했습니다.
- 결제 테스트 케이스  'KakaoPaymentServiceTest'를 리팩토링했습니다.
- 예약 생성 및 오류 처리 테스트 시나리오를 개선하기 위해 'ReservationServiceTest'를 업데이트했습니다.

Feature/view reservation 테스트 코드 수정

---

src/main/java/com/linked/classbridge/domain/OneDayClass.java

- OneDayClass 엔티티 컬럼의 studentCount, totalAge를 초기화 하기위해서 @Builder.Default를 붙여주었습니다.

fix(builder): add superbuilder.default in OneDayClass

---

src/main/java/com/linked/classbridge/config/CorsMvcConfig.java
src/main/java/com/linked/classbridge/config/SecurityConfig.java
src/main/java/com/linked/classbridge/config/WebSocketConfig.java
src/main/java/com/linked/classbridge/oauth2/CustomSuccessHandler.java

- 테스트에서 사용하던 http://localhost:8080 를 https://class-bridge.vercel.app으로 바꾸었습니다.
CorsMvcConfig.java
SecurityConfig.java
CustomSuccessHandler.java

fix(url): replace localhost

---

src/main/java/com/linked/classbridge/service/UserService.java

- null 체크 로직이 추가되었습니다. username이 null이라면 username에 닉네임을 넣습니다.

fix(user service): add null check

---

src/main/java/com/linked/classbridge/service/KakaoPaymentService.java
src/test/http/payment.http
src/test/http/reservation.http
src/test/http/user.http

디버깅을 위한 에러 로그를 추가했습니다.
**AS-IS**
**TO-BE**

Refactor/create payment 에러 로그 추가

---

src/main/java/com/linked/classbridge/config/CorsMvcConfig.java
src/main/java/com/linked/classbridge/config/SecurityConfig.java

debug: 결제 인증 에러 cors, 시큐리티 허용하도록 변경

---

src/main/java/com/linked/classbridge/util/RefundPolicyUtils.java
src/test/http/payment.http

부분환불시 환불 로직에 오류가 있어 수정하였습니다.
**AS-IS**
**TO-BE**

debug: 환불 로직 수정

---

src/main/java/com/linked/classbridge/domain/document/OneDayClassDocument.java
src/main/java/com/linked/classbridge/dto/oneDayClass/ClassDto.java
src/main/java/com/linked/classbridge/dto/oneDayClass/ClassSearchDto.java
src/main/resources/elasticsearch/mapping.json

- class document 에 totalReivews 를 추가하였습니다.
- mapping에 totalReivews를 추가하였습니다.
- classDto 에 address 를 address1, 2, 3으로 분리하였습니다.

Refactor/ add totalReviews in OneDayClassDocument and address to address 1,2,3 in ClassDto

---

src/main/java/com/linked/classbridge/controller/TutorController.java
src/main/java/com/linked/classbridge/controller/UserController.java

- 강사 클래스, faq, tag 관련 role 을 TUTOR 로 추가하였습니다.
- 유저 찜 관련 role 을 USER 로 추가하였습니다.

refactor: add roles for tutor and user

---

src/main/java/com/linked/classbridge/config/CorsMvcConfig.java

- CORS 설정 관련 수정
**AS-IS**
**TO-BE**

debug: cors 설정 수정

---

src/main/java/com/linked/classbridge/config/CorsMvcConfig.java
src/main/java/com/linked/classbridge/config/SecurityConfig.java

debug: cors 설정 수정, localhost:3000 허용

---

src/main/java/com/linked/classbridge/config/WebSocketConfig.java

- WebSocketConfig의 setAllowedOrigins에 localhost를 추가해주었습니다.

fix(config): add localhost for allowed origins

---

src/main/java/com/linked/classbridge/dto/oneDayClass/ClassDto.java
src/main/java/com/linked/classbridge/repository/OneDayClassRepository.java
src/main/java/com/linked/classbridge/service/RecommendationService.java

- ClassDto에 프론트에서 필요한 필드를 추가하였습니다.(tutorName, wish, starRate, 주소 분할)
- 지연로딩이 발생하지 않도록 직접 필드 set을 해주었습니다.
- 변경사항에 따른 테스트 코드를 수정하였습니다.

fix(recommend): add fields in ClassDto

---

src/main/java/com/linked/classbridge/dto/oneDayClass/ClassDto.java
src/main/java/com/linked/classbridge/service/OneDayClassService.java

deploy: Develop -> Release

---

src/main/java/com/linked/classbridge/controller/PaymentController.java
src/main/java/com/linked/classbridge/dto/payment/PaymentPrepareDto.java

- 기존에 String으로 url을 반환하였습니다.
- 객체를 반환하도록 수정했습니다.
**AS-IS**
**TO-BE**

refactor: 결제 요청시 json으로 반환하도록 수정

---

src/main/java/com/linked/classbridge/service/KakaoPaymentService.java

- 결제시 프론트엔드 주소로 반환하도록 수정했습니다.
**AS-IS**
**TO-BE**

refactor: 결제시 프론트엔드 주소로 반환하도록 수정

---

src/main/java/com/linked/classbridge/oauth2/CustomSuccessHandler.java

- 테스트를 위해 vercel.app url을 localhost:3000으로 바꾸었습니다.

fix(success-handler): change redirect url

---

src/main/java/com/linked/classbridge/controller/PaymentController.java
src/main/java/com/linked/classbridge/dto/reservation/SuccessReservationDto.java
src/main/java/com/linked/classbridge/repository/ReservationRepository.java
src/main/java/com/linked/classbridge/service/KakaoPaymentService.java

- SuccessReservationDto 를 생성하여 결제 완료 후 결제 내역에 관한 내용을 redirect body에 넣어서 보내줍니다.

refactor: add SuccessReservationDto

---

src/main/java/com/linked/classbridge/controller/PaymentController.java
src/main/java/com/linked/classbridge/dto/reservation/SuccessReservationDto.java
src/main/java/com/linked/classbridge/oauth2/CustomSuccessHandler.java
src/main/java/com/linked/classbridge/repository/ReservationRepository.java
src/main/java/com/linked/classbridge/service/KakaoPaymentService.java

Develop -> release merge

---

src/main/java/com/linked/classbridge/controller/PaymentController.java
src/main/java/com/linked/classbridge/repository/ReservationRepository.java
src/main/java/com/linked/classbridge/service/KakaoPaymentService.java

- url에 reservationId 와 classId 를 넣어주었습니다.

refactor: add url reservationId and classId

---

src/main/java/com/linked/classbridge/controller/HomeController.java

- / 경로에 대한 No static resource 에러를 해결하기 위해 리다이렉션 컨트롤러를 추가하였습니다.

feat(home-redirect): add redirect to home
